apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
spec:
  selector:
    matchLabels:
      app: prod-app
  replicas: 3
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - production
      containers:
        - image: nginx:latest
          name: nginx
